# Criação de um bucketS3 atraves de um template yaml que será usado no CloudFormation
Description: Criar bucket no S3

Resources:

  BucketGuilhermeRoncatoS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-guilherme-roncato-bootcamp
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True